
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:ReliacoatInventory.App.OnAppStartup_UpdateThemeName(System.Object,System.Windows.StartupEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:ReliacoatInventory.Views.ItemInventory.ItemInventoryExport(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CC0090:You have missing/unexistent parameters in Xml Docs", Justification = "<Pending>", Scope = "member", Target = "~M:XamlGeneratedNamespace.GeneratedInternalTypeHelper.AddEventHandler(System.Reflection.EventInfo,System.Object,System.Delegate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CC0090:You have missing/unexistent parameters in Xml Docs", Justification = "<Pending>", Scope = "member", Target = "~M:XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateDelegate(System.Type,System.Object,System.String)~System.Delegate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CC0090:You have missing/unexistent parameters in Xml Docs", Justification = "<Pending>", Scope = "member", Target = "~M:XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateInstance(System.Type,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CC0090:You have missing/unexistent parameters in Xml Docs", Justification = "<Pending>", Scope = "member", Target = "~M:XamlGeneratedNamespace.GeneratedInternalTypeHelper.GetPropertyValue(System.Reflection.PropertyInfo,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CC0090:You have missing/unexistent parameters in Xml Docs", Justification = "<Pending>", Scope = "member", Target = "~M:XamlGeneratedNamespace.GeneratedInternalTypeHelper.SetPropertyValue(System.Reflection.PropertyInfo,System.Object,System.Object,System.Globalization.CultureInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:ReliacoatInventory.Views.Log.ExportLog(System.Object,System.Windows.RoutedEventArgs)")]